version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    ports:
      - 127.0.0.1:9200:9200
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    restart: always
    ports:
      - 5601:5601

  logstash:
    image: logstash:5.2.1
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/drivers:/usr/share/logstash/drivers
    command: logstash -f /usr/share/logstash/pipeline/*.conf
    network_mode: host
