version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ratmaxi8
      - MYSQL_DATABASE=pldt
    ports:
      - 3306:3306

  data:
    depends_on:
      - mysql
    build: ./mock_data
    ports:
      - 127.0.0.1:5000:5000
    volumes:
      - ./mock_data:/opt/app
    restart: always
    command: python /opt/app/create_db.py
    network_mode: host

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    ports:
      - 127.0.0.1:9200:9200
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    restart: always
    ports:
      - 5601:5601

  logstash:
    depends_on:
      - data
    image: logstash:5.2.1
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./logstash/drivers:/usr/share/logstash/drivers
    command: logstash -f /usr/share/logstash/pipeline/*.conf
    network_mode: host
